/* eslint-disable @typescript-eslint/naming-convention */
const ProductMock = {
  id: 'MLB2935307082',
  site_id: 'MLB',
  title: 'Ford Ecosport 2.0 Xlt 16v',
  seller: {},
  price: 37290,
  prices: {},
  sale_price: null,
  currency_id: 'BRL',
  available_quantity: 1,
  sold_quantity: 0,
  buying_mode: 'classified',
  listing_type_id: 'gold_premium',
  stop_time: '2023-01-09T04:00:00.000Z',
  condition: 'used',
  permalink: 'https://carro.mercadolivre.com.br/MLB-2935307082-ford-ecosport-20-xlt-16v-_JM',
  thumbnail: 'http://http2.mlstatic.com/D_871842-MLB52366724976_112022-I.jpg',
  thumbnail_id: '871842-MLB52366724976_112022',
  accepts_mercadopago: true,
  installments: null,
  address: {},
  promotions: [
  ],
  shipping: {},
  seller_address: {},
  seller_contact: {},
  location: {},
  attributes: [],
  original_price: null,
  category_id: 'MLB1744',
  official_store_id: null,
  domain_id: 'MLB-CARS_AND_VANS',
  catalog_product_id: 'MLB7863180',
  tags: [],
  order_backend: 1,
  use_thumbnail_id: true,
  offer_score: null,
  offer_share: null,
  match_score: null,
  winner_item_id: null,
  melicoin: null,
  discounts: null,
  inventory_id: null,
};

type Product = typeof ProductMock;

export default Product;
